### ISSUE TITLE
Bump OpenSSL version built in the substrate layer

### ISSUE THREAD

**Issue by sjug** [hashicorp/vagrant-installers#108]
Vagrant is not currently compatible with OpenSSL 1.1.0, initial issue was opened https://github.com/mitchellh/vagrant/issues/8621 but it was in the wrong repo.

I would like to be able to use Vagrant with the current version of OpenSSL.

**Comment by soapy1** [comment]
Current openSSL version is [1.1.1k](https://github.com/hashicorp/vagrant-installers/blob/30d4db28cd26f16ebeb86ee0ef7862844dbc6bc7/substrate/run.sh#L21)
