### ISSUE TITLE
Bump Ruby version built in the substrate layer 

### ISSUE THREAD

**Issue by jsteel44** [hashicorp/vagrant-installers#112]
Ruby 2.3 fails to build for me on Arch, maybe because of gcc7. I bumped the Ruby version to 2.4.1 in hiera/common.yaml and that builds fine apart from I see Ruby warnings when running Vagrant commands now. Could you bump the version and get vagrant/vagrant-substrate working properly with Ruby 2.4? I believe this will also resolve the issue #106. Thanks

**Comment by chrisroberts** [comment]
Bumping Vagrant to Ruby 2.4 is still a little ways out. There are some compatibility issues that need to be addressed within the Vagrant code before the 2.4 upgrade will happen within the substrate here, and the ruby constraint defined within Vagrant's gemspec.
