### ISSUE TITLE
64-bit installer always installs in ProgramFiles(x86)

### ISSUE THREAD

**Issue by kolbma** [hashicorp/vagrant-installers#118]
The 64-bit Windows installer always uses the ProgramFiles(x86) directory although I've specified ProgramFiles manually.

**Comment by drujd** [comment]
Still an issue, more than a year later. If you select Program Files from the dialog, Program Files (x86) is used in the text field. Even if you remove the (x86) part, Vagrant is installed to Program Files (x86).

**Comment by aglasson** [comment]
Yep noticed the same issue.
