### ISSUE TITLE
APT repository release file is broken

### ISSUE THREAD

**Issue by codekandis** [hashicorp/vagrant-installers#185]
## Description

Since of today the APT release file is expired.

```
Get:18 https://vagrant-deb.linestarve.com any InRelease [3,938 B]                 
Reading package lists... Done         
E: Release file for https://vagrant-deb.linestarve.com/dists/any/InRelease is expired (invalid since 13h 19min 9s). Updates for this repository will not be applied.
```

## APT source

```
deb https://vagrant-deb.linestarve.com/ any main
```

## System prequisites

* Linux hostname 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

**Comment by codekandis** [comment]
Tried some times today. It's running well now.

**Comment by wolfgang42** [comment]
FYI the repo you mention is not an official HashiCorp offering—support requests for it should be directed to [wolfgang42/vagrant-deb](https://github.com/wolfgang42/vagrant-deb), not HashiCorp. (This particular issue was reported as wolfgang42/vagrant-deb#19, which I've since fixed.)
