### ISSUE TITLE
Ruby 3

### ISSUE THREAD

**Issue by chrisroberts** [hashicorp/vagrant-installers#210]
Update installer builds with latest Ruby 3

Requires: hashicorp/vagrant#12417

**Comment by danowar2k** [comment]
Will Vagrant be updated to Ruby 3?

I'm asking because this would solve a problem with Windows ENV ASCII strings and autoconverting those strings to UTF-8 / UTF-16 which is done in the childprocess library Vagrant uses (to_wide_string).

**Comment by chrisroberts** [comment]
Vagrant packages are now built with Ruby 3. Cheers!
