### ISSUE TITLE
Update AppImage package to use Ruby 3

### ISSUE THREAD

**Issue by soapy1** [hashicorp/vagrant-installers#214]
The AppImage package currently uses ruby 2.6 from ppa:brightbox/ruby-ng. Since there are currently no Ruby 3 deb packages available the approach to building these packages must change some in order to make Ruby 3 available.

Some useful resources:
https://github.com/AppImage/AppImageKit/issues/729
https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps

An attempt:https://github.com/hashicorp/vagrant-installers/compare/main...soapy1:appimage-bump-ruby?expand=1

**Comment by noraj** [comment]
Ruby 3.1 seems available on Debian [bookworm (testing)](https://packages.debian.org/bookworm/ruby) and [sid (unstable)](https://packages.debian.org/sid/ruby)

Debian package tracker:

- [ruby3.0](https://tracker.debian.org/pkg/ruby3.0)
- [ruby3.1](https://tracker.debian.org/pkg/ruby3.1)
