### ISSUE TITLE
Missing Vagrant Releases from APT repository

### ISSUE THREAD

**Issue by rgl** [hashicorp/vagrant-installers#274]
At least the [vagrant 2.3.6 release](https://github.com/hashicorp/vagrant/releases/tag/v2.3.6) is missing from the apt.releases.hashicorp.com APT repository at:

* https://apt.releases.hashicorp.com/dists/jammy/Release
* https://apt.releases.hashicorp.com/dists/jammy/main/binary-amd64/Packages

**Comment by chrisroberts** [comment]
@rgl Thanks for the report! I'm actively working on getting this fixed and it should be resolved shortly.

linking hashicorp/vagrant#13168

**Comment by rgl** [comment]
From my viewpoint, 2.3.5 and 2.3.6 are not yet in the APT repository.

Can you please verify what is going on?
